/* soapStub.h
   Generated by gSOAP 2.8.38 for outfile.h

gSOAP XML Web services tools
Copyright (C) 2000-2016, Robert van Engelen, Genivia Inc. All Rights Reserved.
The soapcpp2 tool and its generated software are released under the GPL.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
--------------------------------------------------------------------------------
A commercial use license is available from Genivia Inc., contact@genivia.com
--------------------------------------------------------------------------------
*/

#include <deque>
#include <list>
#include <vector>
#include <set>
#define SOAP_NAMESPACE_OF_ns2	"urn:calc"

#ifndef soapStub_H
#define soapStub_H
#include "stdsoap2.h"
#if GSOAP_VERSION != 20838
# error "GSOAP VERSION 20838 MISMATCH IN GENERATED CODE VERSUS LIBRARY CODE: PLEASE REINSTALL PACKAGE"
#endif


/******************************************************************************\
 *                                                                            *
 * Types with Custom Serializers                                              *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Classes, Structs and Unions                                                *
 *                                                                            *
\******************************************************************************/

struct ns2__addResponse;	/* outfile.h:317 */
struct ns2__add;	/* outfile.h:317 */
struct ns2__subResponse;	/* outfile.h:388 */
struct ns2__sub;	/* outfile.h:388 */
struct ns2__mulResponse;	/* outfile.h:459 */
struct ns2__mul;	/* outfile.h:459 */
struct ns2__divResponse;	/* outfile.h:530 */
struct ns2__div;	/* outfile.h:530 */
struct ns2__powResponse;	/* outfile.h:601 */
struct ns2__pow;	/* outfile.h:601 */

/* outfile.h:317 */
#ifndef SOAP_TYPE_ns2__addResponse
#define SOAP_TYPE_ns2__addResponse (14)
/* complex XSD type 'ns2:addResponse': */
struct SOAP_CMAC ns2__addResponse {
      public:
        /** Required element 'result' of XSD type 'xsd:double' */
        double result;
      public:
        /** Return unique type id SOAP_TYPE_ns2__addResponse */
        int soap_type() const { return SOAP_TYPE_ns2__addResponse; }
        /** Constructor with member initializations */
        ns2__addResponse()
        {
          result = (double)0;
        }
        /** Friend allocator used by soap_new_ns2__addResponse(struct soap*, int) */
        friend SOAP_FMAC1 ns2__addResponse * SOAP_FMAC2 soap_instantiate_ns2__addResponse(struct soap*, int, const char*, const char*, size_t*);
};
#endif

/* outfile.h:317 */
#ifndef SOAP_TYPE_ns2__add
#define SOAP_TYPE_ns2__add (15)
/* complex XSD type 'ns2:add': */
struct SOAP_CMAC ns2__add {
      public:
        /** Required element 'a' of XSD type 'xsd:double' */
        double a;
        /** Required element 'b' of XSD type 'xsd:double' */
        double b;
      public:
        /** Return unique type id SOAP_TYPE_ns2__add */
        int soap_type() const { return SOAP_TYPE_ns2__add; }
        /** Constructor with member initializations */
        ns2__add()
        {
          a = (double)0;
          b = (double)0;
        }
        /** Friend allocator used by soap_new_ns2__add(struct soap*, int) */
        friend SOAP_FMAC1 ns2__add * SOAP_FMAC2 soap_instantiate_ns2__add(struct soap*, int, const char*, const char*, size_t*);
};
#endif

/* outfile.h:388 */
#ifndef SOAP_TYPE_ns2__subResponse
#define SOAP_TYPE_ns2__subResponse (17)
/* complex XSD type 'ns2:subResponse': */
struct SOAP_CMAC ns2__subResponse {
      public:
        /** Required element 'result' of XSD type 'xsd:double' */
        double result;
      public:
        /** Return unique type id SOAP_TYPE_ns2__subResponse */
        int soap_type() const { return SOAP_TYPE_ns2__subResponse; }
        /** Constructor with member initializations */
        ns2__subResponse()
        {
          result = (double)0;
        }
        /** Friend allocator used by soap_new_ns2__subResponse(struct soap*, int) */
        friend SOAP_FMAC1 ns2__subResponse * SOAP_FMAC2 soap_instantiate_ns2__subResponse(struct soap*, int, const char*, const char*, size_t*);
};
#endif

/* outfile.h:388 */
#ifndef SOAP_TYPE_ns2__sub
#define SOAP_TYPE_ns2__sub (18)
/* complex XSD type 'ns2:sub': */
struct SOAP_CMAC ns2__sub {
      public:
        /** Required element 'a' of XSD type 'xsd:double' */
        double a;
        /** Required element 'b' of XSD type 'xsd:double' */
        double b;
      public:
        /** Return unique type id SOAP_TYPE_ns2__sub */
        int soap_type() const { return SOAP_TYPE_ns2__sub; }
        /** Constructor with member initializations */
        ns2__sub()
        {
          a = (double)0;
          b = (double)0;
        }
        /** Friend allocator used by soap_new_ns2__sub(struct soap*, int) */
        friend SOAP_FMAC1 ns2__sub * SOAP_FMAC2 soap_instantiate_ns2__sub(struct soap*, int, const char*, const char*, size_t*);
};
#endif

/* outfile.h:459 */
#ifndef SOAP_TYPE_ns2__mulResponse
#define SOAP_TYPE_ns2__mulResponse (20)
/* complex XSD type 'ns2:mulResponse': */
struct SOAP_CMAC ns2__mulResponse {
      public:
        /** Required element 'result' of XSD type 'xsd:double' */
        double result;
      public:
        /** Return unique type id SOAP_TYPE_ns2__mulResponse */
        int soap_type() const { return SOAP_TYPE_ns2__mulResponse; }
        /** Constructor with member initializations */
        ns2__mulResponse()
        {
          result = (double)0;
        }
        /** Friend allocator used by soap_new_ns2__mulResponse(struct soap*, int) */
        friend SOAP_FMAC1 ns2__mulResponse * SOAP_FMAC2 soap_instantiate_ns2__mulResponse(struct soap*, int, const char*, const char*, size_t*);
};
#endif

/* outfile.h:459 */
#ifndef SOAP_TYPE_ns2__mul
#define SOAP_TYPE_ns2__mul (21)
/* complex XSD type 'ns2:mul': */
struct SOAP_CMAC ns2__mul {
      public:
        /** Required element 'a' of XSD type 'xsd:double' */
        double a;
        /** Required element 'b' of XSD type 'xsd:double' */
        double b;
      public:
        /** Return unique type id SOAP_TYPE_ns2__mul */
        int soap_type() const { return SOAP_TYPE_ns2__mul; }
        /** Constructor with member initializations */
        ns2__mul()
        {
          a = (double)0;
          b = (double)0;
        }
        /** Friend allocator used by soap_new_ns2__mul(struct soap*, int) */
        friend SOAP_FMAC1 ns2__mul * SOAP_FMAC2 soap_instantiate_ns2__mul(struct soap*, int, const char*, const char*, size_t*);
};
#endif

/* outfile.h:530 */
#ifndef SOAP_TYPE_ns2__divResponse
#define SOAP_TYPE_ns2__divResponse (23)
/* complex XSD type 'ns2:divResponse': */
struct SOAP_CMAC ns2__divResponse {
      public:
        /** Required element 'result' of XSD type 'xsd:double' */
        double result;
      public:
        /** Return unique type id SOAP_TYPE_ns2__divResponse */
        int soap_type() const { return SOAP_TYPE_ns2__divResponse; }
        /** Constructor with member initializations */
        ns2__divResponse()
        {
          result = (double)0;
        }
        /** Friend allocator used by soap_new_ns2__divResponse(struct soap*, int) */
        friend SOAP_FMAC1 ns2__divResponse * SOAP_FMAC2 soap_instantiate_ns2__divResponse(struct soap*, int, const char*, const char*, size_t*);
};
#endif

/* outfile.h:530 */
#ifndef SOAP_TYPE_ns2__div
#define SOAP_TYPE_ns2__div (24)
/* complex XSD type 'ns2:div': */
struct SOAP_CMAC ns2__div {
      public:
        /** Required element 'a' of XSD type 'xsd:double' */
        double a;
        /** Required element 'b' of XSD type 'xsd:double' */
        double b;
      public:
        /** Return unique type id SOAP_TYPE_ns2__div */
        int soap_type() const { return SOAP_TYPE_ns2__div; }
        /** Constructor with member initializations */
        ns2__div()
        {
          a = (double)0;
          b = (double)0;
        }
        /** Friend allocator used by soap_new_ns2__div(struct soap*, int) */
        friend SOAP_FMAC1 ns2__div * SOAP_FMAC2 soap_instantiate_ns2__div(struct soap*, int, const char*, const char*, size_t*);
};
#endif

/* outfile.h:601 */
#ifndef SOAP_TYPE_ns2__powResponse
#define SOAP_TYPE_ns2__powResponse (26)
/* complex XSD type 'ns2:powResponse': */
struct SOAP_CMAC ns2__powResponse {
      public:
        /** Required element 'result' of XSD type 'xsd:double' */
        double result;
      public:
        /** Return unique type id SOAP_TYPE_ns2__powResponse */
        int soap_type() const { return SOAP_TYPE_ns2__powResponse; }
        /** Constructor with member initializations */
        ns2__powResponse()
        {
          result = (double)0;
        }
        /** Friend allocator used by soap_new_ns2__powResponse(struct soap*, int) */
        friend SOAP_FMAC1 ns2__powResponse * SOAP_FMAC2 soap_instantiate_ns2__powResponse(struct soap*, int, const char*, const char*, size_t*);
};
#endif

/* outfile.h:601 */
#ifndef SOAP_TYPE_ns2__pow
#define SOAP_TYPE_ns2__pow (27)
/* complex XSD type 'ns2:pow': */
struct SOAP_CMAC ns2__pow {
      public:
        /** Required element 'a' of XSD type 'xsd:double' */
        double a;
        /** Required element 'b' of XSD type 'xsd:double' */
        double b;
      public:
        /** Return unique type id SOAP_TYPE_ns2__pow */
        int soap_type() const { return SOAP_TYPE_ns2__pow; }
        /** Constructor with member initializations */
        ns2__pow()
        {
          a = (double)0;
          b = (double)0;
        }
        /** Friend allocator used by soap_new_ns2__pow(struct soap*, int) */
        friend SOAP_FMAC1 ns2__pow * SOAP_FMAC2 soap_instantiate_ns2__pow(struct soap*, int, const char*, const char*, size_t*);
};
#endif

/* outfile.h:662 */
#ifndef WITH_NOGLOBAL
#ifndef SOAP_TYPE_SOAP_ENV__Header
#define SOAP_TYPE_SOAP_ENV__Header (28)
/* SOAP_ENV__Header: */
struct SOAP_CMAC SOAP_ENV__Header {
      public:
        /** Return unique type id SOAP_TYPE_SOAP_ENV__Header */
        int soap_type() const { return SOAP_TYPE_SOAP_ENV__Header; }
        /** Constructor with member initializations */
        SOAP_ENV__Header()
        {
        }
        /** Friend allocator used by soap_new_SOAP_ENV__Header(struct soap*, int) */
        friend SOAP_FMAC1 SOAP_ENV__Header * SOAP_FMAC2 soap_instantiate_SOAP_ENV__Header(struct soap*, int, const char*, const char*, size_t*);
};
#endif
#endif

/* outfile.h:662 */
#ifndef WITH_NOGLOBAL
#ifndef SOAP_TYPE_SOAP_ENV__Code
#define SOAP_TYPE_SOAP_ENV__Code (29)
/* Type SOAP_ENV__Code is a recursive data type, (in)directly referencing itself through its (base or derived class) members */
/* SOAP_ENV__Code: */
struct SOAP_CMAC SOAP_ENV__Code {
      public:
        /** Optional element 'SOAP-ENV:Value' of XSD type 'xsd:QName' */
        char *SOAP_ENV__Value;
        /** Optional element 'SOAP-ENV:Subcode' of XSD type 'SOAP-ENV:Code' */
        struct SOAP_ENV__Code *SOAP_ENV__Subcode;
      public:
        /** Return unique type id SOAP_TYPE_SOAP_ENV__Code */
        int soap_type() const { return SOAP_TYPE_SOAP_ENV__Code; }
        /** Constructor with member initializations */
        SOAP_ENV__Code()
        {
          SOAP_ENV__Value = (char *)0;
          SOAP_ENV__Subcode = (struct SOAP_ENV__Code *)0;
        }
        /** Friend allocator used by soap_new_SOAP_ENV__Code(struct soap*, int) */
        friend SOAP_FMAC1 SOAP_ENV__Code * SOAP_FMAC2 soap_instantiate_SOAP_ENV__Code(struct soap*, int, const char*, const char*, size_t*);
};
#endif
#endif

/* outfile.h:662 */
#ifndef WITH_NOGLOBAL
#ifndef SOAP_TYPE_SOAP_ENV__Detail
#define SOAP_TYPE_SOAP_ENV__Detail (31)
/* SOAP_ENV__Detail: */
struct SOAP_CMAC SOAP_ENV__Detail {
      public:
        char *__any;
        /** Any type of element 'fault' assigned to fault with its SOAP_TYPE_T assigned to __type */
        /** Do not create a cyclic data structure throught this member unless SOAP encoding or SOAP_XML_GRAPH are used for id-ref serialization */
        int __type;
        void *fault;
      public:
        /** Return unique type id SOAP_TYPE_SOAP_ENV__Detail */
        int soap_type() const { return SOAP_TYPE_SOAP_ENV__Detail; }
        /** Constructor with member initializations */
        SOAP_ENV__Detail()
        {
          __any = (char *)0;
          __type = 0;
          fault = NULL;
        }
        /** Friend allocator used by soap_new_SOAP_ENV__Detail(struct soap*, int) */
        friend SOAP_FMAC1 SOAP_ENV__Detail * SOAP_FMAC2 soap_instantiate_SOAP_ENV__Detail(struct soap*, int, const char*, const char*, size_t*);
};
#endif
#endif

/* outfile.h:662 */
#ifndef WITH_NOGLOBAL
#ifndef SOAP_TYPE_SOAP_ENV__Reason
#define SOAP_TYPE_SOAP_ENV__Reason (34)
/* SOAP_ENV__Reason: */
struct SOAP_CMAC SOAP_ENV__Reason {
      public:
        /** Optional element 'SOAP-ENV:Text' of XSD type 'xsd:string' */
        char *SOAP_ENV__Text;
      public:
        /** Return unique type id SOAP_TYPE_SOAP_ENV__Reason */
        int soap_type() const { return SOAP_TYPE_SOAP_ENV__Reason; }
        /** Constructor with member initializations */
        SOAP_ENV__Reason()
        {
          SOAP_ENV__Text = (char *)0;
        }
        /** Friend allocator used by soap_new_SOAP_ENV__Reason(struct soap*, int) */
        friend SOAP_FMAC1 SOAP_ENV__Reason * SOAP_FMAC2 soap_instantiate_SOAP_ENV__Reason(struct soap*, int, const char*, const char*, size_t*);
};
#endif
#endif

/* outfile.h:662 */
#ifndef WITH_NOGLOBAL
#ifndef SOAP_TYPE_SOAP_ENV__Fault
#define SOAP_TYPE_SOAP_ENV__Fault (35)
/* SOAP_ENV__Fault: */
struct SOAP_CMAC SOAP_ENV__Fault {
      public:
        /** Optional element 'faultcode' of XSD type 'xsd:QName' */
        char *faultcode;
        /** Optional element 'faultstring' of XSD type 'xsd:string' */
        char *faultstring;
        /** Optional element 'faultactor' of XSD type 'xsd:string' */
        char *faultactor;
        /** Optional element 'detail' of XSD type 'SOAP-ENV:Detail' */
        struct SOAP_ENV__Detail *detail;
        /** Optional element 'SOAP-ENV:Code' of XSD type 'SOAP-ENV:Code' */
        struct SOAP_ENV__Code *SOAP_ENV__Code;
        /** Optional element 'SOAP-ENV:Reason' of XSD type 'SOAP-ENV:Reason' */
        struct SOAP_ENV__Reason *SOAP_ENV__Reason;
        /** Optional element 'SOAP-ENV:Node' of XSD type 'xsd:string' */
        char *SOAP_ENV__Node;
        /** Optional element 'SOAP-ENV:Role' of XSD type 'xsd:string' */
        char *SOAP_ENV__Role;
        /** Optional element 'SOAP-ENV:Detail' of XSD type 'SOAP-ENV:Detail' */
        struct SOAP_ENV__Detail *SOAP_ENV__Detail;
      public:
        /** Return unique type id SOAP_TYPE_SOAP_ENV__Fault */
        int soap_type() const { return SOAP_TYPE_SOAP_ENV__Fault; }
        /** Constructor with member initializations */
        SOAP_ENV__Fault()
        {
          faultcode = (char *)0;
          faultstring = (char *)0;
          faultactor = (char *)0;
          detail = (struct SOAP_ENV__Detail *)0;
          SOAP_ENV__Code = (struct SOAP_ENV__Code *)0;
          SOAP_ENV__Reason = (struct SOAP_ENV__Reason *)0;
          SOAP_ENV__Node = (char *)0;
          SOAP_ENV__Role = (char *)0;
          SOAP_ENV__Detail = (struct SOAP_ENV__Detail *)0;
        }
        /** Friend allocator used by soap_new_SOAP_ENV__Fault(struct soap*, int) */
        friend SOAP_FMAC1 SOAP_ENV__Fault * SOAP_FMAC2 soap_instantiate_SOAP_ENV__Fault(struct soap*, int, const char*, const char*, size_t*);
};
#endif
#endif

/******************************************************************************\
 *                                                                            *
 * Typedefs                                                                   *
 *                                                                            *
\******************************************************************************/


/* outfile.h:101 */
#ifndef SOAP_TYPE__QName
#define SOAP_TYPE__QName (5)
typedef char *_QName;
#endif

/* outfile.h:101 */
#ifndef SOAP_TYPE__XML
#define SOAP_TYPE__XML (6)
typedef char *_XML;
#endif

/******************************************************************************\
 *                                                                            *
 * Serializable Types                                                         *
 *                                                                            *
\******************************************************************************/


/* char has binding name 'byte' for type 'xsd:byte' */
#ifndef SOAP_TYPE_byte
#define SOAP_TYPE_byte (3)
#endif

/* int has binding name 'int' for type 'xsd:int' */
#ifndef SOAP_TYPE_int
#define SOAP_TYPE_int (1)
#endif

/* double has binding name 'double' for type 'xsd:double' */
#ifndef SOAP_TYPE_double
#define SOAP_TYPE_double (11)
#endif

/* struct SOAP_ENV__Fault has binding name 'SOAP_ENV__Fault' for type '' */
#ifndef SOAP_TYPE_SOAP_ENV__Fault
#define SOAP_TYPE_SOAP_ENV__Fault (35)
#endif

/* struct SOAP_ENV__Reason has binding name 'SOAP_ENV__Reason' for type '' */
#ifndef SOAP_TYPE_SOAP_ENV__Reason
#define SOAP_TYPE_SOAP_ENV__Reason (34)
#endif

/* struct SOAP_ENV__Detail has binding name 'SOAP_ENV__Detail' for type '' */
#ifndef SOAP_TYPE_SOAP_ENV__Detail
#define SOAP_TYPE_SOAP_ENV__Detail (31)
#endif

/* struct SOAP_ENV__Code has binding name 'SOAP_ENV__Code' for type '' */
#ifndef SOAP_TYPE_SOAP_ENV__Code
#define SOAP_TYPE_SOAP_ENV__Code (29)
#endif

/* struct SOAP_ENV__Header has binding name 'SOAP_ENV__Header' for type '' */
#ifndef SOAP_TYPE_SOAP_ENV__Header
#define SOAP_TYPE_SOAP_ENV__Header (28)
#endif

/* struct ns2__pow has binding name 'ns2__pow' for type 'ns2:pow' */
#ifndef SOAP_TYPE_ns2__pow
#define SOAP_TYPE_ns2__pow (27)
#endif

/* struct ns2__powResponse has binding name 'ns2__powResponse' for type 'ns2:powResponse' */
#ifndef SOAP_TYPE_ns2__powResponse
#define SOAP_TYPE_ns2__powResponse (26)
#endif

/* struct ns2__div has binding name 'ns2__div' for type 'ns2:div' */
#ifndef SOAP_TYPE_ns2__div
#define SOAP_TYPE_ns2__div (24)
#endif

/* struct ns2__divResponse has binding name 'ns2__divResponse' for type 'ns2:divResponse' */
#ifndef SOAP_TYPE_ns2__divResponse
#define SOAP_TYPE_ns2__divResponse (23)
#endif

/* struct ns2__mul has binding name 'ns2__mul' for type 'ns2:mul' */
#ifndef SOAP_TYPE_ns2__mul
#define SOAP_TYPE_ns2__mul (21)
#endif

/* struct ns2__mulResponse has binding name 'ns2__mulResponse' for type 'ns2:mulResponse' */
#ifndef SOAP_TYPE_ns2__mulResponse
#define SOAP_TYPE_ns2__mulResponse (20)
#endif

/* struct ns2__sub has binding name 'ns2__sub' for type 'ns2:sub' */
#ifndef SOAP_TYPE_ns2__sub
#define SOAP_TYPE_ns2__sub (18)
#endif

/* struct ns2__subResponse has binding name 'ns2__subResponse' for type 'ns2:subResponse' */
#ifndef SOAP_TYPE_ns2__subResponse
#define SOAP_TYPE_ns2__subResponse (17)
#endif

/* struct ns2__add has binding name 'ns2__add' for type 'ns2:add' */
#ifndef SOAP_TYPE_ns2__add
#define SOAP_TYPE_ns2__add (15)
#endif

/* struct ns2__addResponse has binding name 'ns2__addResponse' for type 'ns2:addResponse' */
#ifndef SOAP_TYPE_ns2__addResponse
#define SOAP_TYPE_ns2__addResponse (14)
#endif

/* struct SOAP_ENV__Reason * has binding name 'PointerToSOAP_ENV__Reason' for type '' */
#ifndef SOAP_TYPE_PointerToSOAP_ENV__Reason
#define SOAP_TYPE_PointerToSOAP_ENV__Reason (37)
#endif

/* struct SOAP_ENV__Detail * has binding name 'PointerToSOAP_ENV__Detail' for type '' */
#ifndef SOAP_TYPE_PointerToSOAP_ENV__Detail
#define SOAP_TYPE_PointerToSOAP_ENV__Detail (36)
#endif

/* struct SOAP_ENV__Code * has binding name 'PointerToSOAP_ENV__Code' for type '' */
#ifndef SOAP_TYPE_PointerToSOAP_ENV__Code
#define SOAP_TYPE_PointerToSOAP_ENV__Code (30)
#endif

/* _XML has binding name '_XML' for type '' */
#ifndef SOAP_TYPE__XML
#define SOAP_TYPE__XML (6)
#endif

/* _QName has binding name '_QName' for type 'xsd:QName' */
#ifndef SOAP_TYPE__QName
#define SOAP_TYPE__QName (5)
#endif

/* char * has binding name 'string' for type 'xsd:string' */
#ifndef SOAP_TYPE_string
#define SOAP_TYPE_string (4)
#endif

/******************************************************************************\
 *                                                                            *
 * Externals                                                                  *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Client-Side Call Stub Functions                                            *
 *                                                                            *
\******************************************************************************/

    SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns2__add(struct soap *soap, const char *soap_endpoint, const char *soap_action, double a, double b, double &result);
    SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns2__sub(struct soap *soap, const char *soap_endpoint, const char *soap_action, double a, double b, double &result);
    SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns2__mul(struct soap *soap, const char *soap_endpoint, const char *soap_action, double a, double b, double &result);
    SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns2__div(struct soap *soap, const char *soap_endpoint, const char *soap_action, double a, double b, double &result);
    SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns2__pow(struct soap *soap, const char *soap_endpoint, const char *soap_action, double a, double b, double &result);

/******************************************************************************\
 *                                                                            *
 * Server-Side Operations                                                     *
 *                                                                            *
\******************************************************************************/

    /** Web service operation 'ns2__add' (returns SOAP_OK or error code) */
    SOAP_FMAC5 int SOAP_FMAC6 ns2__add(struct soap*, double a, double b, double &result);
    /** Web service operation 'ns2__sub' (returns SOAP_OK or error code) */
    SOAP_FMAC5 int SOAP_FMAC6 ns2__sub(struct soap*, double a, double b, double &result);
    /** Web service operation 'ns2__mul' (returns SOAP_OK or error code) */
    SOAP_FMAC5 int SOAP_FMAC6 ns2__mul(struct soap*, double a, double b, double &result);
    /** Web service operation 'ns2__div' (returns SOAP_OK or error code) */
    SOAP_FMAC5 int SOAP_FMAC6 ns2__div(struct soap*, double a, double b, double &result);
    /** Web service operation 'ns2__pow' (returns SOAP_OK or error code) */
    SOAP_FMAC5 int SOAP_FMAC6 ns2__pow(struct soap*, double a, double b, double &result);

/******************************************************************************\
 *                                                                            *
 * Server-Side Skeletons to Invoke Service Operations                         *
 *                                                                            *
\******************************************************************************/

extern "C" SOAP_FMAC5 int SOAP_FMAC6 soap_serve(struct soap*);

extern "C" SOAP_FMAC5 int SOAP_FMAC6 soap_serve_request(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns2__add(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns2__sub(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns2__mul(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns2__div(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns2__pow(struct soap*);

#endif

/* End of soapStub.h */
